=== fundi011/Neurology_Website/neuroconsult.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT neurologyconsultform (patientinformation, request, report)>
<!ELEMENT patientinformation (casenumber, patientname, species, breed, sex, dob, weight)>
<!ELEMENT casenumber (#PCDATA)>
<!ELEMENT patientname (#PCDATA)>
<!ELEMENT species (#PCDATA)>
<!ELEMENT breed (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT request (question1+, question2+, question3+, question4+, question5?, question6?, question7?)>
<!ELEMENT question1 (#PCDATA)>
<!ELEMENT question2 (#PCDATA)>
<!ELEMENT question3 (#PCDATA)>
<!ELEMENT question4 (#PCDATA)>
<!ELEMENT question5 (#PCDATA)>
<!ELEMENT question6 (#PCDATA)>
<!ELEMENT question7 (#PCDATA)>
<!ELEMENT report (findings, localization, diagnosis, recommendation)>
<!ELEMENT findings (mentation+, cranialnerves+, gait+, reflexes+, proprioception+, palpation+)>
<!ELEMENT mentation (description1+)>
<!ELEMENT cranialnerves (description2+)>
<!ELEMENT gait (description3+)>
<!ELEMENT reflexes (description4+)>
<!ELEMENT proprioception (description5+)>
<!ELEMENT palpation (description6+)>
<!ELEMENT localization (#PCDATA)>
<!ELEMENT diagnosis (#PCDATA)>
<!ELEMENT recommendation (#PCDATA)>

=== fundi011/Neurology_Website/consult-form.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheet.xsl"?>
<!DOCTYPE neuroconsult SYSTEM "neuroconsult.dtd">
<neurologyconsultform>
    <patientinformation> Patient Information </patientinformation>
        <casenumber> 75214896 </casenumber>
        <patientname> Mishka </patientname>
        <species> Canine </species>
        <breed> Border Collie </breed>
        <sex> Male  </sex>	
        <dob> Jun 15, 2009 </dob>
        <weight> 19 kg </weight>
    <request> </request>
        <question1> Cluster seizures </question1>
	    <question2> Neurological evaluation </question2>
        <question3> First seizure December 2011. Bloodword at that time normal. Presenting today fo 3 grand mal seizures in the past 24 hours. </question3>
        <question4> ER </question4>
        <question5> Hospitalization </question5>
        <question6>  </question6>
        <question7> </question7>
    <report> </report>
        <findings> Findings </findings>
            <mentation> </mentation>
            <cranialnerves> </cranialnerves>
            <gait> </gait>
            <reflexes> </reflexes>
            <proprioception> </proprioception>
            <palpation> </palpation>
        <localization> Localization </localization>
        <diagnosis> Differential Diagnosis </diagnosis>
        <recommendation> Recommendation </recommendation>
</neurologyconsultform>
